<a href="https://colab.research.google.com/github/lalit1511/NumpyLearning/blob/main/numpy_100_challenges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [2]:
# Challenge 1: Import NumPy and print its version
print("Numpy Version:",np.__version__)

# Challenge 2: Create a 1D array of numbers from 0 to 9
arr=np.arange(10)
print(arr)

# Challenge 3: Create a 3x3 NumPy array filled with True
arr2 = np.full((3, 3), True, dtype=bool)
print("\nChallenge 3:\n", arr2)

# Challenge 4: Extract all odd numbers from arr1
odd_numbers=arr[arr%2==1]
print("Odd number from arr\n:", odd_numbers)

# Challenge 5: Replace all odd numbers in arr1 with -1
arr1_mod=np.where(arr%2==1 ,-1,arr)
print("\nChallenge 5 (odds to -1):",arr1_mod)

# Challenge 6: Reshape a 1D array of 10 elements into 2 rows
reshaped_arr = arr.reshape(2, 5)
print("Reshaped array:\n",reshaped_arr)

# Challenge 7: Stack two arrays vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack((a, b))
print("\nChallenge 7:\n", vstacked)

# Challenge 8: Stack the same arrays horizontally
hstacked = np.hstack((a, b))
print("\nChallenge 8:\n", hstacked)

# Challenge 9: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
mat = np.diag([1, 2, 3, 4], k=-1)
print("\nChallenge 9:\n", mat)

# Challenge 10: Create a checkerboard 8x8 matrix (0s and 1s)
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nChallenge 10 (Checkerboard):\n", checkerboard)



Numpy Version: 2.0.2
[0 1 2 3 4 5 6 7 8 9]

Challenge 3:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Odd number from arr
: [1 3 5 7 9]

Challenge 5 (odds to -1): [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Reshaped array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Challenge 7:
 [[1 2 3]
 [4 5 6]]

Challenge 8:
 [1 2 3 4 5 6]

Challenge 9:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

Challenge 10 (Checkerboard):
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
# Challenge 11: Normalize a 1D array (values between 0 and 1)

arr1=np.random.randint(0,100,10)
normalized=(arr1-np.min(arr1))/np.max(arr1)-np.min(arr1)
print("\nChallenge 11:\nOriginal:", arr1)
print("Normalized:", normalized)

# Challenge 12: Multiply a 5x3 matrix by a 3x2 matrix (dot product)
a = np.random.randint(0, 10, size=(5, 3))
b = np.random.randint(0, 10, size=(3, 2))
dot_product = np.dot(a, b)
print("\nChallenge 12:\n", dot_product)


# Challenge 13: Extract the integer part of a random float array
arr = np.random.uniform(0, 10, 5)
int_part = arr.astype(int)
print("\nChallenge 13:\nOriginal:", arr)
print("Integer part:", int_part)

# Challenge 14: Get the positions where elements of two arrays match
a=np.array([1,2,3,2,3,4,5])
b=np.array([1,2,3,3,4,5,6])
matches=np.where(a==b)
print("matches")

# Challenge 15: Replace elements of array that are greater than a value
arr2 = np.array([10, 20, 30, 40, 50])
arr2[arr2>30]=30
print("Elements greater than 30 :", arr2)

# Challenge 16: Swap two rows in a 2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3[[0, 1]] = arr3[[1, 0]]
print("\nChallenge 16:\nRow swapped array:\n", arr3)

# Challenge 17: Get the top 3 maximum values in an array
arr4 = np.array([10, 20, 30, 40, 50])
top_3_max = np.sort(arr4)[-3:]
print(top_3_max)

# Challenge 18: Count how many elements are greater than a threshold
arr = np.random.randint(0, 100, 20)
count = np.sum(arr > 50)
print("\nChallenge 18:\nArray:", arr)
print("Count > 50:", count)

# Challenge 19: Get unique elements and their counts
arr = np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(arr, return_counts=True)
print("\nChallenge 19:\nValues:", values)
print("Counts:", counts)

# Challenge 20: Get boolean mask of elements between two values
arr = np.arange(10, 30)
mask = (arr > 15) & (arr < 25)
print("\nChallenge 20:\nBoolean Mask:", mask)
print("Filtered values:", arr[mask])


Challenge 11:
Original: [46 30 48 92 49 31 97 50 73  4]
Normalized: [-3.56701031 -3.73195876 -3.54639175 -3.09278351 -3.53608247 -3.72164948
 -3.04123711 -3.5257732  -3.28865979 -4.        ]

Challenge 12:
 [[ 0  0]
 [40 48]
 [29 62]
 [16 60]
 [10 12]]

Challenge 13:
Original: [6.5361905  3.92861333 9.08577576 2.01457997 9.78490209]
Integer part: [6 3 9 2 9]
matches
Elements greater than 30 : [10 20 30 30 30]

Challenge 16:
Row swapped array:
 [[4 5 6]
 [1 2 3]
 [7 8 9]]
[30 40 50]

Challenge 18:
Array: [70 52 23 92 24 81 82 60 60 44  4 12 31 12 51 78 74 12 90 66]
Count > 50: 12

Challenge 19:
Values: [1 2 3 4]
Counts: [1 2 3 1]

Challenge 20:
Boolean Mask: [False False False False False False  True  True  True  True  True  True
  True  True  True False False False False False]
Filtered values: [16 17 18 19 20 21 22 23 24]


In [4]:
# Challenge 21: Create an array of 10 values and convert them to float
arr=np.arange(10)
arr=arr.astype(float)
print(arr)

# Challenge 22: Create a 2D array and center it (subtract mean of each column)
arr = np.random.randint(0, 100, (5, 5))
centered_arr = arr - np.mean(arr, axis=0)
print(centered_arr)

# Challenge 23: Compute the Euclidean distance between two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dist=np.linalg.norm(a-b)
print("\nChallenge 23:\nEuclidean Distance:", dist)

# Challenge 24: Find the most frequent value in an array
arr = np.random.randint(0, 10, 20)
most_freq = np.bincount(arr).argmax()
print("\nChallenge 24:\nArray:", arr)
print("Most frequent:", most_freq)

# Challenge 25: Find the n largest values in an array
arr = np.random.randint(0, 100, 15)
n = 5
largest = np.sort(arr)[-5:]
print("\nChallenge 25:\nArray:", arr)
print(f"Top {n} largest:", largest)

# Challenge 26: Create a 10x10 matrix and get the sum of diagonal
mat = np.random.randint(0, 100, (10, 10))
diag_sum = np.trace(mat)
print("\nChallenge 26:\nMatrix:\n", mat)
print("Diagonal sum:", diag_sum)

# Challenge 27: Check if two arrays are equal (element-wise)
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
equal=np.array_equal(a, b)
print("\nChallenge 27:\nArray 1:", a)
print("Array 2:", b)
print("Equal:", equal)

# Challenge 28: Make an array immutable (read-only)
arr = np.array([1, 2, 3])
arr.flags.writeable = False
#arr[0] = 10  # This will raise a ValueError

# Challenge 29: Reverse the rows of a 2D array
arr = np.arange(9).reshape(3, 3)
reversed_rows = arr[::-1]
print("\nChallenge 29:\nReversed Rows:\n", reversed_rows)

# Challenge 30: Reverse the columns of a 2D array
reversed_cols = arr[:, ::-1]
print("\nChallenge 30:\nReversed Columns:\n", reversed_cols)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[ 11.  -38.6  12.2  16.   -2.4]
 [ -7.   45.4  10.2 -31.  -12.4]
 [  9.  -13.6 -22.8  18.    5.6]
 [ -4.    0.4  22.2  29.    4.6]
 [ -9.    6.4 -21.8 -32.    4.6]]

Challenge 23:
Euclidean Distance: 5.196152422706632

Challenge 24:
Array: [9 2 2 6 3 5 6 3 4 6 2 6 9 0 8 8 4 3 2 4]
Most frequent: 2

Challenge 25:
Array: [33 23 28 46 50 36 31 91 87 39 80 25 31  7 65]
Top 5 largest: [50 65 80 87 91]

Challenge 26:
Matrix:
 [[24 63 75 63 72 53 44 85 55 94]
 [34 91  3 24  8  6 96 12 82 25]
 [44 44  5 31 27 91 72 33 88 88]
 [87 26 68 31 15  6 50 37 91 90]
 [41 57  8 61 15 12 84 98 29 88]
 [14 83 84 19 98 22 48 53 66 80]
 [52 52 59 17 24 11 47 61 49 86]
 [ 0 10 17 11 74 50 97 71 54 10]
 [84 37 67  4 93 90  6 11 46 66]
 [16 52  4  2 12 53 44 66 75 63]]
Diagonal sum: 415

Challenge 27:
Array 1: [1 2 3]
Array 2: [1 2 4]
Equal: False

Challenge 29:
Reversed Rows:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]

Challenge 30:
Reversed Columns:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [11]:
# Challenge 31: Swap columns in a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
swapped = arr[:, [2, 1, 0]]
print("\nChallenge 31:\nSwapped Columns:\n", swapped)

#Explanation of arr[:, [2, 1, 0]] means all rows,[2, 1, 0] → means take columns in reverse order,That’s why:,Column 2 becomes first,Column 1 stays in the middle,Column 0 becomes last

# Challenge 32: Replace max value in an array with 0
arr = np.random.randint(1, 100, 10)
print(arr)
arr[arr.argmax()] = 0
print("\nChallenge 32:\nModified Array:", arr)

# Challenge 33: Compute row-wise mean of a 2D array
arr = np.random.randint(1, 10, (4, 3))
row_means = np.mean(arr, axis=1)
print("\nChallenge 33:\nRow Means:", row_means)

## Challenge 34: Compute column-wise median of a 2D array
column_means=np.mean(arr , axis=0)
print("\nChallenge 34:\nColumn-wise Medians:", column_means)

## Challenge 35: Flatten a 2D array into 1D
flattened=arr.flatten()
print("\nChallenge 35:\nFlattened Array:", flattened)

# Challenge 36: Sort an array by the second column
arr = np.array([[1, 9, 3], [5, 1, 2], [4, 6, 0]])
sorted_arr = arr[arr[:, 1].argsort()]
print("\nChallenge 36:\nSorted by 2nd Column:\n", sorted_arr)

# Challenge 38: Save and load a NumPy array file
arr=np.random.rand(5)
np.save("test_array.npy",arr)
loaded_arr=np.load("test_array.npy")
print("\nChallenge 38:\nLoaded Array:", loaded_arr)

## Challenge 39: Get the indices of non-zero elements
arr=np.array([1,2,0,0,4,0])
non_zero_indices=np.where(arr!=0)
print("\nChallenge 39:\nNon-Zero Indices:", non_zero_indices)

# Challenge 40: Clip values in an array (e.g., limit between 10 and 20)
arr = np.array([5, 10, 15, 25, 30])
clipped=np.clip(arr,10,20)
print("\nChallenge 40:\nClipped Array:", clipped)


Challenge 31:
Swapped Columns:
 [[3 2 1]
 [6 5 4]]
[60 58 74 11 19 80 88 42 95 74]

Challenge 32:
Modified Array: [60 58 74 11 19 80 88 42  0 74]

Challenge 33:
Row Means: [4.         5.33333333 5.33333333 4.66666667]

Challenge 34:
Column-wise Medians: [4.  4.5 6. ]

Challenge 35:
Flattened Array: [4 2 6 4 6 6 5 2 9 3 8 3]

Challenge 36:
Sorted by 2nd Column:
 [[5 1 2]
 [4 6 0]
 [1 9 3]]

Challenge 38:
Loaded Array: [0.35995569 0.53056048 0.1605645  0.76208117 0.79779673]

Challenge 39:
Non-Zero Indices: (array([0, 1, 4]),)

Challenge 40:
Clipped Array: [10 10 15 20 20]


In [19]:
# Challenge 41: Create a 2D array of shape (8, 3) and normalize each row (L2 norm)
arr = np.random.rand(8, 3)
normed=arr / np.linalg.norm(arr, axis=1, keepdims=True)
print("\nChallenge 41:\nNormalized Array:\n", normed)

#Challenge 42: Subtract the mean of each row from itself
arr=np.random.rand(5,3)
subtracted=arr-np.mean(arr,axis=1,keepdims=True)
print("\nChallenge 42:\nSubtracted Array:\n",subtracted)

# Challenge 43: Sort each row of a 2D array
arr = np.random.randint(0, 100, (3, 5))
sorted_rows=np.sort(arr, axis=1)
print("\nChallenge 43:\nSorted Rows:\n", sorted_rows)

# Challenge 44: Sort each column of a 2D array
sorted_cols = np.sort(arr, axis=0)
print("\nChallenge 44:\nSorted Columns:\n", sorted_cols)

# Challenge 45: Find the most frequent value in an array
arr = np.random.randint(0, 10, 50)
counts = np.bincount(arr)
most_freq = np.argmax(counts)
print("\nChallenge 45:\nArray:", arr)
print("Most frequent:", most_freq)

# Challenge 46: Count unique values and their counts
values, counts = np.unique(arr, return_counts=True)
print("\nChallenge 46:\nUnique Values:", values)
print("Counts:", counts)

# Challenge 47: Replace all odd numbers with -1
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print("\nChallenge 47:\nOdds Replaced with -1:", arr)

# Challenge 48: Replace all odd numbers with -1 (without changing original)
arr = np.arange(10)
modified = np.where(arr % 2 == 1, -1, arr)
print("\nChallenge 48:\nNon-destructive Replace:", modified)

# Challenge 49: Convert a float array to integer type
arr = np.random.rand(5) * 10
converted = arr.astype(int)
print("\nChallenge 49:\nInteger Converted Array:", converted)

# Challenge 50: Create a C-contiguous array from a non-contiguous one
arr = np.arange(12).reshape(3, 4)
non_contig = arr[:, ::2]  # Non-contiguous (slicing every 2nd column)
contig = np.ascontiguousarray(non_contig)
print("\nChallenge 50:\nContiguous Array:\n", contig)





Challenge 41:
Normalized Array:
 [[0.65552868 0.32077167 0.68365758]
 [0.60082393 0.35539699 0.71603323]
 [0.57242312 0.45059511 0.68505169]
 [0.24227949 0.53734116 0.80781503]
 [0.327486   0.15410433 0.93220426]
 [0.81428551 0.30676943 0.49277948]
 [0.9221301  0.08988759 0.37629285]
 [0.12256855 0.28476755 0.95072835]]

Challenge 42:
Subtracted Array:
 [[ 0.07371348  0.10577303 -0.17948651]
 [ 0.02637942 -0.27345019  0.24707077]
 [ 0.07601121 -0.29897069  0.22295948]
 [ 0.21814113 -0.15642132 -0.06171981]
 [ 0.22758326 -0.51712205  0.28953879]]

Challenge 43:
Sorted Rows:
 [[39 41 50 50 88]
 [11 11 30 87 98]
 [38 51 51 57 68]]

Challenge 44:
Sorted Columns:
 [[11 30 11 51 50]
 [38 41 39 87 57]
 [50 68 51 88 98]]

Challenge 45:
Array: [8 0 2 1 1 0 2 5 6 4 5 9 3 8 4 6 2 9 7 7 6 5 8 1 9 9 2 8 3 9 8 0 4 7 8 3 3
 1 2 1 9 0 6 1 5 8 4 7 1 8]
Most frequent: 8

Challenge 46:
Unique Values: [0 1 2 3 4 5 6 7 8 9]
Counts: [4 7 5 4 4 4 4 4 8 6]

Challenge 47:
Odds Replaced with -1: [ 0 -1  2 -1  

In [29]:
# Challenge 51: Find the position of the first occurrence of a value greater than 10
arr = np.array([1, 3, 5, 12, 7, 20])
index = np.argmax(arr > 10)
print("\nChallenge 51:\nFirst Index > 10:", index)

# Challenge 52: Find the indices where elements of one array exist in another
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
indices = np.where(np.in1d(a, b))[0]
print("\nChallenge 52:\nIndices in 'a' where elements exist in 'b':", indices)

# Challenge 53: Create a record array from a (flat) regular array
arr = np.array([("Lalit", 24, 75.5), ("Anu", 22, 64.0)],
               dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print("\nChallenge 53:\nRecord Array:\n", arr)

# Challenge 54: Convert a 1D array of length 12 to a 3D array (2x3x2)
arr=np.arange(12)
reshaped=arr.reshape(2,3,2)
print("\nChallenge 54:\n3D Array:\n", reshaped)

# Challenge 55: Extract all elements between 5 and 15 from an array
arr = np.arange(20)
filtered = arr[(arr > 5) & (arr < 15)]
print("\nChallenge 55:\nElements between 5 and 15:", filtered)

# Challenge 56: Convert a Python list to a NumPy array and back
py_list = [1, 2, 3]
to_np = np.array(py_list)
back_to_list = to_np.tolist()
print("\nChallenge 56:\nBack to List:", back_to_list)

arr=np.zeros((1000,1000))
memory=arr.nbytes
print("\nChallenge 58:\nMemory Used (Bytes):", memory)

# Challenge 59: Create a 1D array of 10 random integers between 1 and 100 and clip values between 20 and 80
arr=np.random.randint(1,100,10)
clipped=np.clip(arr,20,80)
print("\nChallenge 59:\nOriginal:", arr)
print("\nChallenge 59:\nClipped Array:", clipped)

arr=np.random.rand(100)
mean=np.mean(arr)
median=np.median(arr)
std_dev=np.std(arr)
print("\nChallenge 60:\nMean:", mean)
print("\nChallenge 60:\nMedian:", median)


Challenge 51:
First Index > 10: 3

Challenge 52:
Indices in 'a' where elements exist in 'b': [2 3]

Challenge 53:
Record Array:
 [('Lalit', 24, 75.5) ('Anu', 22, 64. )]

Challenge 54:
3D Array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Challenge 55:
Elements between 5 and 15: [ 6  7  8  9 10 11 12 13 14]

Challenge 56:
Back to List: [1, 2, 3]

Challenge 58:
Memory Used (Bytes): 8000000

Challenge 59:
Original: [28 89 10 88 14  4 42  5 49 59]

Challenge 59:
Clipped Array: [28 80 20 80 20 20 42 20 49 59]

Challenge 60:
Mean: 0.5530125326937931

Challenge 60:
Median: 0.5727743089859523


<ipython-input-29-f7fde48bb7a2>:9: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  indices = np.where(np.in1d(a, b))[0]


In [45]:
# Challenge 61: Swap two columns in a 2D array
arr=np.arange(12).reshape(3,4)
swapped=arr[:,[1,0,2,3]]
print(arr)
print("\nChallenge 61:\nSwapped Columns:\n", swapped)

# Challenge 62: Swap two rows in a 2D array
swapped_rows=arr[[1,0,2],:]
print("\nChallenge 62:\nSwapped Rows:\n", swapped_rows)

# Challenge 63: Reverse the rows of a 2D array
reverse_rows=arr[::-1,:]
print(reverse_rows)
print("\nChallenge 63:\nReversed Rows:\n", reverse_rows)

# Challenge 64: Reverse the columns of a 2D array
reverse_col=arr[:,::-1]
print("\nChallenge 64:\nReversed Columns:\n", reversed_cols)

# Challenge 65: Create a 5x5 matrix with row values ranging from 0 to 4
row_matrix=np.tile(np.arange(5),(5,1))
print("\nChallenge 65:\nRow Matrix:\n", row_matrix)
#np.tile(arr, (5, 1))-This tiles or repeats the array —

# Challenge 66: Create a 5x5 matrix with column values ranging from 0 to 4
col_matrix=np.tile(np.arange(5),(5,1)).T
print(col_matrix)
print("\nChallenge 66:\nColumn Matrix:\n", col_matrix)

# Challenge 67: Get the nth column of a 2D array
nth_col=arr[:,2]
print("\nChallenge 67:\n3rd Column:", nth_col)

# Challenge 68: Get the nth row of a 2D array
nth_row=arr[2,:]
print("\nChallenge 68:\n3rd Row:", nth_row)

# Challenge 69: Replace negative values in an array with 0
arr = np.array([1, -3, 5, -2, 7])
arr[arr<0]=0
print("\nChallenge 69:\nNegatives Replaced with 0:", arr)

# Challenge 70: Get the indices of non-zero elements in an array
arr = np.array([0, 1, 0, 3, 0, 5])
indices = np.nonzero(arr)
print("\nChallenge 70:\nIndices of Non-Zero Elements:", indices)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Challenge 61:
Swapped Columns:
 [[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]

Challenge 62:
Swapped Rows:
 [[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

Challenge 63:
Reversed Rows:
 [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

Challenge 64:
Reversed Columns:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]

Challenge 65:
Row Matrix:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

Challenge 66:
Column Matrix:
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

Challenge 67:
3rd Column: [ 2  6 10]

Challenge 68:
3rd Row: [ 8  9 10 11]

Challenge 69:
Negatives Replaced with 0: [1 0 5 0 7]

Challenge 70:
Indices of Non-Zero Elements: (array([1, 3, 5]),)


In [49]:
#Challenge 71-80
# Challenge 71: Find common values between two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
common=np.intersect1d(a,b)
print("\nChallenge 71:\nCommon Elements:", common)

# Challenge 72: Find differences between two arrays
diff = np.setdiff1d(a, b)
print("\nChallenge 72:\nElements in 'a' not in 'b':", diff)

# Challenge 73: Get the union of two arrays
union = np.union1d(a, b)
print("\nChallenge 73:\nUnion:", union)

# Challenge 75: Normalize an array (0 to 1 range)
arr = np.random.randint(1, 100, 10)
normalized_arr=(arr-arr.min())/(arr.max()-arr.min())
print("\nChallenge 75:\nNormalized Array:", normalized_arr)

# Challenge 76: One-hot encode a NumPy array
arr = np.array([0, 1, 2])
one_hot = np.eye(3)[arr]
print("\nChallenge 76:\nOne-hot Encoded:\n", one_hot)

# Challenge 77: Convert boolean array to int
bool_arr = np.array([True, False, True])
int_arr = bool_arr.astype(int)
print("\nChallenge 77:\nConverted to Int:", int_arr)

# Challenge 78: Multiply a matrix by a scalar
mat = np.array([[1, 2], [3, 4]])
scaled = mat * 10
print("\nChallenge 78:\nMatrix Scaled by 10:\n", scaled)

# Challenge 79: Transpose a matrix
transposed = mat.T
print("\nChallenge 79:\nTransposed Matrix:\n", transposed)

# Challenge 80: Flatten a multi-dimensional array
arr = np.array([[1, 2], [3, 4], [5, 6]])
flat = arr.flatten()
print("\nChallenge 80:\nFlattened Array:", flat)


Challenge 71:
Common Elements: [4 5]

Challenge 72:
Elements in 'a' not in 'b': [1 2 3]

Challenge 73:
Union: [1 2 3 4 5 6 7 8]

Challenge 75:
Normalized Array: [0.57291667 0.6875     0.33333333 0.92708333 0.55208333 0.
 0.92708333 0.44791667 1.         0.82291667]

Challenge 76:
One-hot Encoded:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Challenge 77:
Converted to Int: [1 0 1]

Challenge 78:
Matrix Scaled by 10:
 [[10 20]
 [30 40]]

Challenge 79:
Transposed Matrix:
 [[1 3]
 [2 4]]

Challenge 80:
Flattened Array: [1 2 3 4 5 6]
