<a href="https://colab.research.google.com/github/lalit1511/NumpyLearning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Project 1: NumPy Basics Playground

import numpy as np

print("📌 NumPy Version:", np.__version__)

# 1. Array Creation
arr1 = np.array([1, 2, 3, 4])
print("\n1D Array:", arr1)

arr2 = np.array([[1, 2], [3, 4]])
print("\n2D Array:\n", arr2)

# 2. Array Initialization
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
range_arr = np.arange(10)
linspace_arr = np.linspace(0, 1, 5)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nRange array:", range_arr)
print("\nLinspace array:", linspace_arr)

# 3. Array Properties
print("\nShape:", arr2.shape)
print("Size:", arr2.size)
print("Datatype:", arr2.dtype)

# 4. Indexing and Slicing
print("\nElement at index 2 in arr1:", arr1[2])
print("Slice arr1[1:3]:", arr1[1:3])
print("Last element in arr1:", arr1[-1])

# 5. Reshape & Flatten
reshaped = arr2.reshape(4, 1)
flattened = arr2.ravel()

print("\nReshaped (4,1):\n", reshaped)
print("Flattened array:", flattened)

# 6. Boolean Indexing
print("\nElements > 2 in arr1:", arr1[arr1 > 2])


📌 NumPy Version: 2.0.2

1D Array: [1 2 3 4]

2D Array:
 [[1 2]
 [3 4]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Range array: [0 1 2 3 4 5 6 7 8 9]

Linspace array: [0.   0.25 0.5  0.75 1.  ]

Shape: (2, 2)
Size: 4
Datatype: int64

Element at index 2 in arr1: 3
Slice arr1[1:3]: [2 3]
Last element in arr1: 4

Reshaped (4,1):
 [[1]
 [2]
 [3]
 [4]]
Flattened array: [1 2 3 4]

Elements > 2 in arr1: [3 4]


In [2]:
import numpy as np

In [4]:
print("Numpy verison:", np.__version__)

#Array creation:
arr1=np.array([1,2,3,4])

print("\n1D Array:",arr1)

arr2=np.array([[1,2],[3,4]])
print("\n 2D array:\n ",arr2 )

#Array Initialization

Zeroes=np.zeros((2,3))
Ones=np.ones((2,3))
range_arr=np.arange(10)
linespace_arr=np.linspace(0,1,5)

print("\nZeroes:\n",Zeroes)
print("\nOnes:\n",Ones)
print("\nRange_arr:\n", range_arr)
print("\nLinespace_arr:\n",linespace_arr)

#Array properties
print("\nShape:", arr2.shape)
print("\nSize:", arr2.size)
print("\nDataType:", arr2.dtype)

# 4. Indexing and Slicing
print("\nElement at position 2 in arr1:",arr1[2])
print("Slice arr1[1:3]:", arr1[1:3])
print("Last element in arr1:", arr1[-1])

#5 Reshape & flatten
Reshaped=arr2.reshape(4,1)
Flattened=arr2.ravel()

print("\nReshaped (4,1):\n", reshaped)
print("Flattened array:", flattened)

# 6. Boolean Indexing
print("\nElements > 2 in arr1:", arr1[arr1 > 2])

Numpy verison: 2.0.2

1D Array: [1 2 3 4]

 2D array:
  [[1 2]
 [3 4]]

Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Range_arr:
 [0 1 2 3 4 5 6 7 8 9]

Linespace_arr:
 [0.   0.25 0.5  0.75 1.  ]

Shape: (2, 2)

Size: 4

DataType: int64

Element at position 2 in arr1: 3
Slice arr1[1:3]: [2 3]
Last element in arr1: 4

Reshaped (4,1):
 [[1]
 [2]
 [3]
 [4]]
Flattened array: [1 2 3 4]

Elements > 2 in arr1: [3 4]
