<a href="https://colab.research.google.com/github/lalit1511/NumpyLearning/blob/main/numpy_math_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create 2D Array
data=np.array([[10,20,30],[40,50,60]])
print("\nOriginal Data: ", data)

#Element-wise operations
print("\nAdd 5 :\n",data+5)
print("Multiply by 2:\n", data*2)

#Aggregate statistics

print("\nMean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

# Axis-based operations
print("\nRow-wise sum (axis=1):", np.sum(data, axis=1))
print("Column-wise mean (axis=0):", np.mean(data, axis=0))

# Other useful functions
print("\nClip values between 15 and 45:\n", np.clip(data, 15, 45))
print("Unique values:", np.unique(data))
print("Sorted (flattened):", np.sort(data, axis=None))


Original Data:  [[10 20 30]
 [40 50 60]]

Add 5 :
 [[15 25 35]
 [45 55 65]]
Multiply by 2:
 [[ 20  40  60]
 [ 80 100 120]]

Mean: 35.0
Median: 35.0
Standard Deviation: 17.07825127659933
Variance: 291.6666666666667

Row-wise sum (axis=1): [ 60 150]
Column-wise mean (axis=0): [25. 35. 45.]

Clip values between 15 and 45:
 [[15 20 30]
 [40 45 45]]
Unique values: [10 20 30 40 50 60]
Sorted (flattened): [10 20 30 40 50 60]


In [5]:
# Normalize the data
normalized=(data-np.min(data))/(np.max(data)-np.min(data))
print("\nNormalizes data:\n",normalized)

#Calculate Z-score
Z_scores=(data-np.mean(data))/(np.std(data))
print("\nZ-scores:\n", Z_scores)


Normalizes data:
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]]

Z-scores:
 [[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]
