<a href="https://colab.research.google.com/github/lalit1511/NumpyLearning/blob/main/numpy_matrix_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# 1. Define 2 matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

# 2. Matrix Addition & Subtraction
print('\nA+B:\n', A+B)
print('\nA-B:\n',A-B)


# 3. Matrix Multiplication
print("\nDot product using np.dot:\n:", np.dot(A,B))
print("\nMatrix multiplication using @:\n", A@B)

# 4. Transpose
print("\nTranspose of A:\n", A.T)

# 5. Identity Matrix
I = np.eye(2)
print("\nIdentity Matrix (2x2):\n", I)

# 6. Inverse (only works if matrix is non-singular)
inv_A=np.linalg.inv(A)
print("\nInverse of A:\n",inv_A)

# 7. Determinant
det_A=np.linalg.det(A)
print("\nDeterminant of A:",det_A)

# 8. Rank
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

# 9. Check Inverse (A * A_inv should be Identity)
check_identity = A @ inv_A
print("\nA * A_inv (should be Identity):\n", check_identity)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

A+B:
 [[ 6  8]
 [10 12]]

A-B:
 [[-4 -4]
 [-4 -4]]

Dot product using np.dot:
: [[19 22]
 [43 50]]

Matrix multiplication using @:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Identity Matrix (2x2):
 [[1. 0.]
 [0. 1.]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004
Rank of A: 2

A * A_inv (should be Identity):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
