<a href="https://colab.research.google.com/github/lalit1511/NumpyLearning/blob/main/numpy_random_simulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
# Project 4: NumPy Random Simulations
# 1. Random integers and floats
rand_ints=np.random.randint(1,10, size=(3,3))
rand_floats=np.random.rand(3,3)

print("Random integer:\n",rand_ints)
print("Random floats:\n",rand_floats)

# 2. Set seed for reproducibility
np.random.seed(42)
print("\nSeeded Random Integers:\n", np.random.randint(0, 100, 5))

# 3. Simulate a coin toss (0 = tails, 1 = heads)
coin_tosses=np.random.choice([0,1], size=10)
print("\nCoin Toss Results:", coin_tosses)

# 4. Simulate dice rolls
dice_rolls = np.random.randint(1, 7, size=10)
print("Dice Rolls:", dice_rolls)

# 5. Shuffling an array
arr=np.arange(10)
np.random.shuffle(arr)
print("Shuffled array\n:",arr)

# 6. Random sampling without replacement
sample = np.random.choice(arr, size=5, replace=False)
print("Random Sample (no replacement):", sample)

# 7. Normal distribution simulation
norm_data = np.random.normal(loc=50, scale=10, size=1000)
print("\nGenerated Normal Data (first 10):", norm_data[:10])

Random integer:
 [[3 7 4]
 [9 3 5]
 [3 7 5]]
Random floats:
 [[0.45049925 0.01326496 0.94220176]
 [0.56328822 0.3854165  0.01596625]
 [0.23089383 0.24102547 0.68326352]]

Seeded Random Integers:
 [51 92 14 71 60]

Coin Toss Results: [0 0 1 0 0 0 0 1 0 1]
Dice Rolls: [3 6 5 2 4 6 6 2 4 5]
Shuffled array
: [1 7 6 2 8 9 3 4 5 0]
Random Sample (no replacement): [7 9 8 5 1]

Generated Normal Data (first 10): [44.74877149 69.12771271 29.73280384 61.19423612 57.79192635 38.98902244
 61.30228194 53.73118915 46.13527049 38.41229758]
